apiVersion: v1
kind: List
metadata:
  name: "bds-perceptor components"
  resourceVersion: "0.0.1"
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: perceptor
    namespace: bds-perceptor
    labels:
      app: perceptor-app
  spec:
    replicas: 1
    selector:
      name: bds-perceptor
    template:
      metadata:
        labels:
          name: bds-perceptor
        name: perceptor
        namespace: bds-perceptor
      spec:
        containers:
          - name: perceptor
            image: mfenwickbd/perceptor:latest
            imagePullPolicy: Always
            command:
              - ./perceptor
            ports:
              - containerPort: 3000
            resources:
              requests:
                memory: 2Gi
                cpu: 50m
              limits:
                cpu: 500m
  #          env:
  #          - name: ENV1
  #             value:
  #          - name: ENV2
  #            value:
            terminationMessagePath: /dev/termination-log
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
- apiVersion: v1
  kind: Service
  metadata:
    name: perceptor
    namespace: bds-perceptor
  spec:
    selector:
      name: bds-perceptor
    ports:
    - nodePort: 0
      port: 3001
      protocol: TCP
      targetPort: 3000
